name: Build on Version Change

on:
  push:
    paths:
      - 'app/build.gradle.kts'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if versionName was modified
        id: version_check
        run: |
          if git diff HEAD~1 HEAD -- app/build.gradle.kts | grep -q 'versionName'; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up JDK 11
        if: steps.version_check.outputs.version_changed == 'true'
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        if: steps.version_check.outputs.version_changed == 'true'
        run: chmod +x gradlew

      - name: Run Gradle build
        if: steps.version_check.outputs.version_changed == 'true'
        run: ./gradlew build
